### PR TITLE
Diff Before Upload comparing filesize and last modified time.

### PR DESCRIPTION
**Pull request by filipegar**
Well, I think I've achieved this in a very good way.
To fix bug #26 and #84 I created a routine that gets a list of everything on bucket and conflicts with the collections of $assets received to upload. I check last modified time and file size. If both are different, the file passes this validation and gets uploaded.

### CODE REVIEW

**Comment by filipegar** [comment]
Travis failed on hhvm due to 'yield'. :\

**Comment by publiux** [comment]
I think this is a great PR. I created a fork of this project that I intend to maintain since this one seems slow to implement simple fixes. It is located at https://github.com/publiux/laravelcdn . I have integrated your pull request into the fork and have provided you with appropriate credit for the code. Thanks!

**Comment by filipegar** [comment]
Any news about this one?

**Comment by Mulkave** [comment]
Sorry for the delay on this one, will merge and allow failures on HHVM since it's not required as first-class support in this package.

**Comment by filipegar** [comment]
@Mulkave Great! Could you also push these changes to a new version on packagist? :) thanks.

**Comment by Mulkave** [comment]
@filipegar all up now, thanks a bunch :smile:

**Pull request merged**
